{% set name = "lion-pytorch" %}
{% set version = "0.2.2" %}
{% set python_min = "3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lion_pytorch-{{ version }}.tar.gz
  sha256: 46ad3eca1a57c383acc05a503d6b087344cfc23e3f63ecbcb8a6392bc034f7a2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pytorch >=1.6

test:
  imports:
    - lion_pytorch
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/lucidrains/lion-pytorch
  summary: Lion Optimizer for Pytorch
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
